# Generated by Django 2.0.5 on 2018-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('path', models.FilePathField(allow_files=False, allow_folders=True, path='D:\\Uni\\Masterarbeit', recursive=True)),
            ],
            options={
                'db_table': 'collectionexplorer_collection',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(default='')),
                ('path', models.FilePathField(path='D:\\Uni\\Masterarbeit\\Beispieldaten\\Wiki_partial_corpus', recursive=True)),
                ('date', models.DateTimeField(verbose_name='date created')),
            ],
            options={
                'db_table': 'collectionexplorer_document',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('frequency', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('person', 'Person'), ('location', 'Ort'), ('organization', 'Organisation'), ('other', 'Weitere')], max_length=50)),
            ],
            options={
                'db_table': 'collectionexplorer_entity',
            },
        ),
        migrations.CreateModel(
            name='Ngram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bigram', 'Bigram'), ('trigram', 'Trigram')], max_length=10)),
                ('method', models.CharField(choices=[('pmi', 'Pointwise Mutual Information'), ('most_frequent', 'Häufigste N-Gramme')], max_length=20)),
                ('word1', models.CharField(max_length=512)),
                ('word2', models.CharField(max_length=512)),
                ('word3', models.CharField(blank=True, max_length=512)),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'collectionexplorer_ngram',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='entities',
            field=models.ManyToManyField(blank=True, to='CollectionExplorer.Entity'),
        ),
        migrations.AddField(
            model_name='document',
            name='ngrams',
            field=models.ManyToManyField(blank=True, to='CollectionExplorer.Ngram'),
        ),
        migrations.AddField(
            model_name='collection',
            name='documents',
            field=models.ManyToManyField(blank=True, to='CollectionExplorer.Document'),
        ),
        migrations.AddField(
            model_name='collection',
            name='entities',
            field=models.ManyToManyField(blank=True, to='CollectionExplorer.Entity'),
        ),
        migrations.AddField(
            model_name='collection',
            name='ngrams',
            field=models.ManyToManyField(blank=True, to='CollectionExplorer.Ngram'),
        ),
    ]
