# Generated by Django 2.0 on 2017-12-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='result',
        ),
        migrations.RemoveField(
            model_name='query',
            name='in_history',
        ),
        migrations.RemoveField(
            model_name='query',
            name='in_result',
        ),
        migrations.AddField(
            model_name='history',
            name='query',
            field=models.ManyToManyField(to='search.Query'),
        ),
        migrations.AddField(
            model_name='result',
            name='document',
            field=models.ManyToManyField(to='search.Document'),
        ),
        migrations.AddField(
            model_name='result',
            name='query',
            field=models.ManyToManyField(to='search.Query'),
        ),
    ]
