# Generated by Django 2.0 on 2017-12-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20171215_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(allow_folders=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.FilePathField(path='D:/Uni/Masterarbeit/Beispieldaten/'),
        ),
    ]
