# Generated by Django 2.0 on 2017-12-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20171215_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
    ]
