# Generated by Django 2.0 on 2017-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20171215_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='documents',
            field=models.ManyToManyField(to='search.Document'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.FilePathField(allow_folders=True, path='D:\\Uni\\Masterarbeit\\Beispieldaten', recursive=True),
        ),
    ]
