# Generated by Django 2.0.2 on 2018-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20171215_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='documents',
            field=models.ManyToManyField(blank=True, to='search.Document'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='D:\\Uni\\Masterarbeit', recursive=True),
        ),
    ]
