# Generated by Django 2.0.2 on 2018-02-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20180225_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='changes',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
